apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - .webhooks[0].failurePolicy # gets updated by istiod dynamically
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio-auth/overlays/prod
    repoURL: https://github.com/superorbital/argo-examples.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true