apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-auth
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio-auth/overlays/prod
    repoURL: https://github.com/superorbital/argo-examples.git
    targetRevision: argocd-istio
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
