apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake # this has to be populated with a valid clustersecretstore
    kind: ClusterSecretStore
  target:
    name: application-secret
