apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    valuesInline:
      defaultRevision: default
  - name: istiod
    releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system

# resources:
# - ../../base
# - agent-auth.yaml
#
# patches:
#   - path: istio-configmap.yaml
#   - path: external-secret.yaml
