apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret.yaml

helmCharts:
  - name: base
    releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
  - name: istiod
    releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
