apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    includeCRDs: true
    valuesInline:
      defaultRevision: default
  - name: istiod
    releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system

resources:
  - external-secret.yaml
  - namespace.yaml