apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: application-secret
  data:
  - secretKey: SIGSCI_ACCESSKEYID
    remoteRef:
      key: sigsci_accesskeyid
      version: v1
  - secretKey: SIGSCI_SECRETACCESSKEY
    remoteRef:
      key: sigsci_secretaccesskey
      version: v1
